# Generated by Django 4.2.2 on 2023-08-05 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_date', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='member_pictures/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Non Active', 'Non Active')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_hard.member')),
            ],
        ),
    ]
