# Generated by Django 4.2.2 on 2023-08-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_hard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='captured_picture',
            field=models.ImageField(blank=True, null=True, upload_to='captured_pictures/'),
        ),
    ]
